Repository snap-bug/snap-bug-cli, pull requests merged in 2025-03, with the labels that each got.

#19 feat: Puppeteer 적용 (#18)
  eslint.config.mjs
  package-lock.json
  package.json
  src/puppeteer/browser.js
  src/puppeteer/stateTracker.js
  src/stateTracker.js
  src/utils/config.js
Labels: feat

#21 feat: WebSocket 적용 (#17)
  src/commands/start.js
  src/puppeteer/stateTracker.js
  src/server/server.js
  src/utils/config.js
Labels: feat

#23 fix: 상태 파일 미생성 및 JSON 저장 에러 해결
  bin/index.js
  package-lock.json
  package.json
  src/commands/start.js
  src/puppeteer/browser.js
  src/puppeteer/stateTracker.js
  src/server/server.js
  src/utils/config.js
Labels: fix, refactor

#24 feat: 상태 추적 종료 [snapbug end] (#20)
  src/commands/end.js
  src/commands/start.js
Labels: feat

#29 refactor: 기능 변경에 따른 코드 및 패키지 정리
  package-lock.json
  package.json
  src/commands/start.js
  src/puppeteer/stateTracker.js
  src/server/server.js
  src/utils/config.js
Labels: refactor

#31 feat: RESTful 서버 API 구축 (#26)
  package-lock.json
  package.json
  src/commands/end.js
  src/commands/start.js
  src/server/server.js
  src/utils/config.js
  src/utils/fileUtils.js
  src/utils/httpStatusCode.js
Labels: feat

#32 feat: 상태 변경시 돔트리 정보 추출
  src/puppeteer/stateTracker.js
  src/utils/config.js
Labels: feat

#33 feat: 변경된 리액트 상태 정보를 API로 전송 처리 (#25)
  src/puppeteer/stateTracker.js
Labels: feat

#37 refactor: 서버 실행 방식 개선 및 코드 스타일 최적화
  src/commands/start.js
  src/puppeteer/stateTracker.js
  src/server/server.js
Labels: refactor

#38 refactor: DOM 변경시 자동 감지 로직으로 개선
  src/puppeteer/stateTracker.js
Labels: refactor

#40 docs: PR 목적과 작업 사유를 명확히 하기 위한 템플릿 개선
  .github/pull_request_template.md
Labels: docs

#42 fix: 상태가 한번만 불려오고 추적되지 않던 현상 해결 (#41)
  src/puppeteer/stateTracker.js
Labels: fix

#43 feat: 상태 변경 시 DOM 트리 저장 기능 구현
  src/puppeteer/stateTracker.js
Labels: feat

#45 refactor: Puppeteer 패키지 제거 후 코드 정리 (#44)
  bin/index.js
  package-lock.json
  package.json
  src/cdn/stateTracker.js
  src/commands/end.js
  src/commands/start.js
  src/puppeteer/browser.js
  src/puppeteer/stateTracker.js
  src/server/server.js
Labels: refactor

#47 feat: snapbug run 명령어 추가 및 실행로직 구현
  .github/pull_request_template.md
  .gitignore
  bin/index.js
  package-lock.json
  package.json
  src/commands/end.js
  src/commands/run.js
  src/utils/fileUtils.js
  src/utils/util.js
Labels: feat

#49 refactor: 상태 히스토리 JSON 경로를 config 기반으로 정리
  bin/index.js
  src/commands/run.js
  src/utils/config.js
  src/utils/fileUtils.js
Labels: refactor

#51 feat: Vercel 배포 결과 URL 출력 추가
  .gitignore
  bin/index.js
  package-lock.json
  package.json
  src/commands/run.js
  src/server/server.js
  src/utils/util.js
Labels: feat

#54 fix: 상태 JSON 저장 시 오류 해결 (#53)
  src/server/server.js
Labels: fix

#55 refactor: snapbug run 배포 로직 개선
  bin/index.js
  package-lock.json
  package.json
  src/commands/run.js
Labels: fix, refactor

#58 fix: snapbug-state.json이 snap-bug-client로 정상 복사되지 않는 문제 해결
  package-lock.json
  package.json
  public/snapbug-state.json
  src/cdn/stateTracker.js
  src/commands/run.js
Labels: fix
